---
- name: Set up NFS client
  hosts: "{{ target_host }}"
  become: true
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install nfs-common
      apt:
        name: nfs-common
        state: present

    - name: Create NFS mount directory
      file:
        path: {{ client_mount_path }}
        state: directory
        mode: '0755'

    - name: Add NFS entry to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ nfs_server_host }}:{{ server_mount_path }} {{ client_mount_path }} nfs defaults 0 0"
        state: present
        create: yes

    - name: Mount all file systems
      command: mount -a
      args:
        warn: false
