---
- name: Set up NFS client
  hosts: "{{ target_host }}"
  become: true
  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Install nfs-common
      apt:
        name: nfs-common
        state: present
