# Run as ansible user and let ansible become the user to execute k8s command
---
- name: Configure k8s worker
  hosts: "{{ target_host }}"
  become: true
  become_user: root
  
  tasks:
    - name: Update APT package cache
      become: true
      apt:
        update_cache: yes

    - name: Disable UFW
      ufw:
        state: disabled
    
    - name: Run K3s worker installation
      shell: |
        curl -sfL https://get.k3s.io | K3S_TOKEN=kubernetes@demo sh -s - agent \
        --server https://{{ load_balancer_host }}:6443
      register: k3s_install
      failed_when: k3s_install.rc != 0

    - name: Check K3s agent status
      command: systemctl status k3s-agent
      register: k3s_status
      changed_when: false
