# Run as ansible user and let ansible become the user to execute k8s command
---
- name: Configure k8s worker
  hosts: "{{ target_host }}"
  become: true
  become_user: root
  
  tasks:

    - name: Define K3s installation parameters
      set_fact:
        k3s_version: "v1.31.4+k3s1"
        k3s_token: "kubernetes@demo"
        
    - name: Update APT package cache
      become: true
      apt:
        update_cache: yes

    - name: Disable UFW
      ufw:
        state: disabled
    
    - name: Run K3s worker installation
      shell: |
      if ! command -v k3s-agent >/dev/null; then
        curl -sfL https://get.k3s.io | INSTALL_K3S_VERSION={{ k3s_version }} K3S_TOKEN={{ k3s_token }} sh -s - agent \
        --server https://{{ load_balancer_host }}:6443;
      fi
