apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${PVC_NAME}
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ${ACCESS_MODE}
  resources:
    requests:
      storage: ${PVC_STORAGE}
  storageClassName: ${STORAGE_CLASS}
