apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${METADATA_NAME}
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ${ACCESS_MODE}
  resources:
    requests:
      storage: ${PVC_STORAGE}
  storageClassName: ${PVC_STORAGE_CLASS}
