---
- name: Create wildcard tls secret
  hosts: "{{ target_host }}"
  become: true
  become_user: root
  tasks:

    - name: Create folder for tls config
      file:
        path: /root/wildcard-tls
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create tls secret
      shell: |
        kubectl create secret tls wildcard-cert \
        --cert=ansible/k3s/wildcard-cert/domain-name.crt \
        --key=ansible/k3s/wildcard-cert/domain-name.key -n "{{ namespace }}" 
      environment:
        KUBECONFIG: "/root/.kube/config.yaml"
