---
- name: Create wildcard tls secret
  hosts: "{{ target_host }}"
  become: true
  become_user: root
  tasks:

    - name: Create folder for tls config
      file:
        path: /root/wildcard-tls
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Copy wildcard cert
      copy:
        src: "{{ playbook_dir }}/domain-name.crt"
        dest: /root/wildcard-tls/domain-name.crt
        owner: root
        group: root
        mode: '0644'

    - name: Copy wildcard key
      copy:
        src: "{{ playbook_dir }}/domain-name.key"
        dest: /root/wildcard-tls/domain-name.key
        owner: root
        group: root
        mode: '0644'

    - name: Create tls secret
      shell: |
        kubectl create secret tls wildcard-cert \
        --cert=domain-name.crt \
        --key=domain-name.key -n ingress
      args:
        chdir: /root/wildcard-tls
      environment:
        KUBECONFIG: "/root/.kube/config.yaml"

    - name: Update Nginx Ingress installation 
      command: >
        helm upgrade ingress-nginx nginx-stable/nginx-ingress \
          --namespace ingress \
          --set controller.wildcardTLS.secret="ingress/wildcard-cert"
      environment:
        KUBECONFIG: "/root/.kube/config.yaml"
