apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: promethues-pvc
  namespace: "${NAMESPACE}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: ${PVC_STORAGE}
  storageClassName: "${PVC_STORAGE_CLASS}"
