apiVersion: v1
kind: PersistentVolume
metadata:
  name: harbor-pv
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/k3s-stg/harbor
    server: 43.74.40.116
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "harbor-pv"

