apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /srv/nfs/k3s-stg/monitoring
    server: ${NFS_SERVER_HOST}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "monitoring-pv"

