apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: monitoring-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: "monitoring-pv"
