---
- name: Install Ingress with Helm
  hosts: "{{ target_host }}"
  become: true
  become_user: root
  tasks:

    - name: Add Nginx Ingress Helm repository
      shell: |
        helm repo add nginx-stable https://helm.nginx.com/stable
      args:
        executable: /bin/bash

    - name: Install Nginx Ingress
      command: >
        helm install ingress-nginx nginx-stable/nginx-ingress \
          --version 1.3.1 \
          --namespace ingress --create-namespace \
          --set controller.ingressClass.name=nginx \
          --set controller.ingressClassResource.default=true \
          --set controller.service.loadBalancerIP="{{ ingress_load_balancer_host }}"
      environment:
        KUBECONFIG: "/root/.kube/config.yaml"

