---
- name: Install Helm
  hosts: "{{ target_host }}"
  become: true
  become_user: root
  tasks:

    - name: Add Helm GPG key
      shell: curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
      args:
        executable: /bin/bash

    - name: Install apt-transport-https
      apt:
        name: apt-transport-https
        state: present

    - name: Add Helm apt repository
      shell: |
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" > /etc/apt/sources.list.d/helm-stable-debian.list
      args:
        creates: /etc/apt/sources.list.d/helm-stable-debian.list
        
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Helm
      apt:
        name: helm
        state: present
