---
- name: Install Ingress with Helm
  hosts: "{{ target_host }}"
  become: true
  become_user: root
  tasks:

    - name: Add Nginx Ingress Helm repository
      shell: |
        helm repo add nginx-stable https://helm.nginx.com/stable
      args:
        executable: /bin/bash

    - name: Check if ingress namespace exists
      kubernetes.core.k8s_info:
        kind: Namespace
        name: ingress
      register: namespace_check
      ignore_errors: yes

    - name: Create the ingress namespace if it doesn't exist
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: ingress
      when: namespace_check.failed

    - name: Install Nginx Ingress
      command: >
        helm install ingress-nginx nginx-stable/nginx-ingress \
          --version 1.3.1 \
          --namespace ingress \
          --set controller.ingressClass.name=nginx \
          --set controller.ingressClass.setAsDefault=true \
          --set controller.service.loadBalancerIP="{{ ingress_load_balancer_host }}"
      environment:
        KUBECONFIG: "/root/.kube/config.yaml"

