---
- name: Install Ingress with Helm
  hosts: "{{ target_host }}"
  become: true
  become_user: root
  tasks:

    - name: Add Nginx Ingress Helm repository
      shell: |
        helm repo add nginx-stable https://helm.nginx.com/stable
      args:
        executable: /bin/bash

    - name: Pull Ingress chart
      shell: |
        helm pull nginx-stable/nginx-ingress --version 1.3.1
      args:
        chdir: "/root"
        creates: "/root/nginx-ingress-1.3.1.tgz"

    - name: Extract Ingress chart
      shell: |
        tar -xf nginx-ingress-1.3.1.tgz
      args:
        chdir: "/root"
        creates: "/root/nginx-ingress"

    - name: Prepare values.yaml nginx-ingress helm chart
      template:
        src: files/ingress_values.yaml
        dest: /root/nginx-ingress
        owner: root
        group: root
        mode: '0644'

    - name: Install Nginx Ingress
      shell: |
        helm install nginx-ingress -f values.yaml . -n "{{ namespace }}" --create-namespace
      args:
        chdir: "/root/nginx-ingress"
      environment:
        KUBECONFIG: "/root/.kube/config.yaml"

