---
- name: Install MetalLB with Helm
  hosts: "{{ target_host }}"
  become: true
  become_user: root
  tasks:

    - name: Add MetalLB Helm repository
      shell: |
        helm repo add metallb https://metallb.github.io/metallb
      args:
        executable: /bin/bash

    - name: Create folder for MetalLB config
      file:
        path: /root/metallb
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Configure ip pool
      template:
        src: templates/ipaddresspool.yaml.j2
        dest: /root/metallb/ipaddresspool.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Configure L2 advertisement
      template:
        src: templates/L2advertisement.yaml.j2
        dest: /root/metallb/L2advertisement.yaml
        owner: root
        group: root
        mode: '0644'

    - name: Install metallb
      shell: |
        helm install metallb metallb/metallb \
        --version 0.13.12 \
        --namespace "{{ namespace }}" --create-namespace
      environment:
        KUBECONFIG: "/root/.kube/config.yaml"

    - name: Wait for MetalLB pods to be ready
      shell: |
        kubectl wait --for=condition=Ready pods -l app.kubernetes.io/name=metallb -n {{ namespace }} --timeout=300s
      environment:
        KUBECONFIG: "/root/.kube/config.yaml"

    - name: Apply IPAddressPool configuration
      shell: |
        kubectl apply -f /root/metallb/ipaddresspool.yaml
      environment:
        KUBECONFIG: "/root/.kube/config.yaml"
    
    - name: Apply L2Advertisement configuration
      shell: |
        kubectl apply -f /root/metallb/L2advertisement.yaml
      environment:
        KUBECONFIG: "/root/.kube/config.yaml"
